# Generated by Django 5.2.6 on 2025-10-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="users/default_user.png",
                null=True,
                upload_to="users/",
                verbose_name="Аватар",
            ),
        ),
    ]
