# Generated by Django 5.2.6 on 2025-09-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="authors",
            field=models.CharField(default="Администратор", max_length=300),
        ),
        migrations.AddField(
            model_name="post",
            name="preview",
            field=models.ImageField(blank=True, null=True, upload_to="blog/"),
        ),
        migrations.AddField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
