# Generated by Django 5.2.6 on 2025-09-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_authors_post_preview_post_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="authors",
            field=models.CharField(
                default="Антон",
                help_text="Перечисляйте авторов через запятую",
                max_length=500,
            ),
        ),
    ]
