# Generated by Django 5.2.6 on 2025-10-13 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_options_post_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="owner",
        ),
    ]
