# Generated by Django 5.2.6 on 2025-10-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                default="product_images/default_product.jpg",
                null=True,
                upload_to="products/",
            ),
        ),
    ]
