# Generated by Django 5.2.6 on 2025-10-03 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        0.01, message="Цена должна быть положительной"
                    ),
                    django.core.validators.MaxValueValidator(
                        9999999.99, message="Максимальная цена: 9 999 999.99 руб"
                    ),
                ],
            ),
        ),
    ]
